fhir-server.com/website/views.py
from distutils.errors import DistutilsFileError
from flask import Blueprint, render_template, request, json, redirect, url_for, flash, send_file
from flask_login import login_required, current_user
import requests
import time
import csv
import pathlib
import os 

from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from .models import Users, Users_roles, Nom_roles, Metatags, Questionnaire, Answers, Patients
from . import db 
from .controler import saveform, formsrulesupdate, createCSVid, save_raspuns, insert_db_from_import
from .file_to_fhir import createFHIR
from .import_questionaire import import_questionaire

from datetime import datetime

from sqlalchemy import desc

from pydoc import doc

views = Blueprint('views', __name__)

@views.route('/refreshforms')
@login_required
def refreshforms():
    time.sleep(5)
    return redirect(url_for('views.home'))

@views.route('/')
# @login_required
def public_page():
    return render_template("public_page/public_page.html")

@views.route('/home')
@login_required
def home():
    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()
    metatagsRez = Metatags.query.all()
    answersParinte = Users.query.join(Users_roles, Users.id_users == Users_roles.user_id).add_columns(Users.id_users, Users.first_name, Users.last_name, Users.password, Users.username, Users_roles.role).filter(Users_roles.parinte == current_user.id_users).all()

    questParinte = "publisher=" + current_user.username

    questionnaireAll = Questionnaire.query.order_by(Questionnaire.id_questionnaire.desc()).all()
    path = os.getcwd() + 'files'

    return render_template("home.html", user=current_user, formulare=questionnaireAll, metatags=metatagsRez, roles=userRole, right=userRight, cale=path)

    
@views.route('/create_form/')
@login_required
def create_form():
    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()

    if '12' in userRight.user_right:
        return render_template("create_form.html", user=current_user, roles=userRole, right=userRight)
    else:
        return redirect(url_for('views.home'))


@views.route('/createform/', methods=['POST'])
@login_required
def createform():
    if request.method == 'POST':
        asd = request.json

        x = saveform(asd, 0)

    return {'rez': x}

@views.route('/create_form_edit/<id>')
@login_required
def create_form_edit(id):
    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()
    
    questionnaire = Questionnaire.query.filter_by(id_questionnaire=id).first()
    rezQuestion = json.loads(questionnaire.json_data)

    rez = []

    rez.append({
        "type": "header",
        "label": rezQuestion['title']
    })

    for x in rezQuestion['item']:
        elem = {}
        
        if x['type'] == 'choice':
            val = []
            if 'extension' in x:
                elem['type'] = 'select'
            else:
                elem['type'] = 'checkbox-group'

            for y in x['answerOption']:
                elemVal = {}
                elemVal['label'] = y['valueString']
                val.append(elemVal)
            elem['values'] = val 
        elif x['type'] == 'boolean':
            elem['type'] = 'radio-group'
            elem['values'] = [{"label": "Yes","value": "yes","selected": 'false'},{"label": "No","value": "no","selected": 'false'}]
        elif x['type'] == 'integer':
            elem['type'] = 'number'
            elem['min'] = x['extension'][1]['valueInteger']
            elem['max'] = x['extension'][2]['valueInteger']
            elem['step'] = x['extension'][3]['valueInteger']

        else:
            elem['type'] = x['type']
            elem['className'] = 'form-control'

        elem['label'] = x['text']

        rez.append(elem)

    metatagsRez = Metatags.query.filter_by(id_questionnaire=rezQuestion['id']).first()

    if metatagsRez != None:
        rez.append(
            {
                "type": "text",
                "label": "Metatags",
                "className": "form-control",
                "name": "Metatags",
                "value": metatagsRez.metatags
            })

    idStr = str(rezQuestion['id'])
    rez.append({
            "type": "hidden",
            "name": "id",
            "value": idStr,
        })

    return render_template("create_form_edit.html", user=current_user, id = rezQuestion['id'], continut = rez, roles=userRole, right=userRight)

@views.route('/createformedit/', methods=['POST'])
@login_required
def createformedit():
    if request.method == 'POST':
        asd = request.json

        for elem in asd:
            if elem['type'] == 'hidden':
                id = elem['value']

        x = saveform(asd, id)

    return {'rez': x}

@views.route('/createrules/<id>')
@login_required
def createrules(id):
    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()

    questionnaire = Questionnaire.query\
        .filter_by(id_questionnaire=id)\
        .first()
    
    rezQuestion = json.loads(questionnaire.json_data)

    key = 'enableWhen'
    i = 0
    for x in rezQuestion['item']:
        
        if key in x:
            for y in x['enableWhen']:
                if y['answerBoolean']:
                    rez = int(y['answerBoolean'] == True)
                    rezQuestion['item'][i]['enableWhen'][0]['answerBoolean'] = rez
                else:
                    rez = int(y['answerBoolean'] == False)
                    rezQuestion['item'][i]['enableWhen'][0]['answerBoolean'] = rez
        i = i + 1

    rules = []

    return render_template("question_rules.html", user=current_user, continut = rezQuestion, roles=userRole, right=userRight)

@views.route('/formsrulessave/', methods=['POST'])
@login_required
def formsrulessave():
    if request.method == 'POST':
        
        rezRules = request.form['data']
        id_new = formsrulesupdate(rezRules)

    return redirect(url_for('views.home'))

@views.route('/form/<id>')
@login_required
def form(id):

    questionnaire = Questionnaire.query\
            .filter_by(id_questionnaire=id)\
            .first()
    
    rezQuestion = json.loads(questionnaire.json_data)
    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()

    patientsAll = Patients.query.order_by(Patients.id_patient).all()
    getPateints = []
    for elem in patientsAll:
        getPateints.append(json.loads(elem.json_data))

    return render_template("form.html", user=current_user, question = rezQuestion, patients = getPateints, id = id, roles=userRole, right=userRight)

@views.route('/saveRaspuns/', methods = ['POST'])
@login_required
def saveRaspuns():
    
    raspText = request.form
    save_raspuns(raspText)
    
    return redirect(url_for('views.show_answers'))

@views.route('/show_answers')
@login_required
def show_answers():

    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()

    questionnaireResponse = Answers.query.order_by(Answers.id_answers.desc()).all()

    return render_template("answers.html", user=current_user, formulare = questionnaireResponse, roles=userRole, right=userRight)

@views.route('/answer/<id>')
@login_required
def answer(id):

    answer = Answers.query\
        .filter_by(id_answers=id)\
        .first()
    rezAnswer = json.loads(answer.json_data)

    question = Questionnaire.query\
        .filter_by(id_questionnaire=answer.id_question)\
        .first()
    questionTitle = question.title

    userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    userRight = Nom_roles.query.filter_by(code=userRole.role).first()
    
    return render_template('answer.html', user=current_user, answer = rezAnswer, id = id, qTitle = questionTitle, roles=userRole, right=userRight)   

@views.route('/sterge/<id>/<tip>')
@login_required
def sterge(id, tip):

    if tip == 'Questionnaire':
        question = Questionnaire.query\
            .filter_by(id_questionnaire=id)\
            .delete();
        db.session.commit()
        # return render_template("home.html", user=current_user, formulare=content, roles=userRole, right=userRight)
        return redirect(url_for('views.home'))
    if tip == 'QuestionnaireResponse':
        answer = Answers.query\
            .filter_by(id_answers=id)\
            .delete();
        db.session.commit()
        # return render_template("answers.html", user=current_user, formulare = content, roles=userRole, right=userRight)
        return redirect(url_for('views.show_answers'))



    # API_ENDPOINT = "http://localhost:8080/fhir/"+ tip +"/" + id + "?_pretty=true"
    # r = requests.delete(url = API_ENDPOINT) 

    # if r.status_code == 200:
    #     API_ENDPOINT = "http://localhost:8080/fhir/"+ tip +"?_sort=-_id&_pretty=true"
    #     r = requests.get(url=API_ENDPOINT)
    #     content = r.json()
    #     userRole = Users_roles.query.filter_by(user_id=current_user.id_users).first()
    #     userRight = Nom_roles.query.filter_by(code=userRole.role).first()

    #     if tip == 'Questionnaire':
    #         return render_template("home.html", user=current_user, formulare=content, roles=userRole, right=userRight)
    #     if tip == 'QuestionnaireResponse':
    #         return render_template("answers.html", user=current_user, formulare = content, roles=userRole, right=userRight)
    # else:
    #     raise Exception(r.json())

# user admin

@views.route('/sign-up/', defaults={'id': None}, methods=['GET', 'POST'])

fhir-server.com/website/templates/answer.html
{% extends "base.html" %}
{% block title %}Forms{% endblock %}

{% block content %}

<script>
    function printData()
    {
       var divToPrint=document.getElementById("printAnswer");
       newWin= window.open("");
       newWin.document.write(divToPrint.outerHTML);
       newWin.print();
       newWin.close();
    }
    
    </script>

<button class="btn btn-primary float-right" onclick="printData()">
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-printer" viewBox="0 0 16 16">
    <path d="M2.5 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
    <path d="M5 1a2 2 0 0 0-2 2v2H2a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h1v1a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-1h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-1V3a2 2 0 0 0-2-2H5zM4 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2H4V3zm1 5a2 2 0 0 0-2 2v1H2a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1v-1a2 2 0 0 0-2-2H5zm7 2v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1z"/>
</svg>
</button>

<div id="printAnswer">
    <div class="text-center mt-3">
        <h1>Questionnaire {{qTitle}}</h1>
    </div>
    <hr>
    <h3>
        Patient: {{answer['subject']['display']}}
    </h3>
    
    <hr>
   

    {% for elem in answer['item'] %}


        {% set list1 = elem['text'].split('~') %}
        
        {% if list1[3] == 'choice' %}
            {% if curId is not defined %}   
                aa{{ elem['text'] }}: 
                {% set curId = list1[0] %}
                AICI {{ curId }}
            {% else %}
                {% if curId != list1[0] %}    
                    {{ elem['text'] }}: 
                    {% set curId = list1[0] %}
                    JOS
                {% endif %}
            {% endif %}

        
        {% else %}
            <p class="font-weight-bold">{{ elem['text'] }}:</p> 
        {% endif %}


        {% for elem2 in elem['answer'] %}

            {% for key, val in elem2.items() %}
                {% if key == "valueString" %}
                    {% if val == 'true' %}
                        <p class="text-justify">Yes</p>
                    {% elif val == 'false' %}
                        <p class="text-justify">No</p>
                    {% else %}
                        <p class="text-justify">{{ val }}</p>
                    {% endif %}
                {% endif %}
                {% if key == "valueBoolean" %}
                    {% if val == True %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                {% endif %}
            {% endfor %}
            

        {% endfor %}
        <br>
    {% endfor %}

</div>
{% endblock %}

fhir-server.com/website/templates/answers.html
{% extends "base.html" %}
{% block title %}Create Forms{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-4">
            <h1>Answers</h1>
        </div>
        <div class="col-md-8">
            
            <a href="/export">
                <button class="btn btn-primary float-right mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                    </svg>
                </button>
            </a>
        </div>
    </div>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">                
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTableAnswer" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Actions</th>
                                        <th >Tags</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Actions</th>
                                        <th >Tags</th>
                                    </tr>
                                </tfoot>
                                <tbody>

{% for elem in formulare %}

{% set data = elem['date_created'] %}
{% set time = elem['time_created'] %}


<tr>
<td>{{ loop.index }}</td>
<td>
    <a href="/answer/{{ elem['id_answers'] }}">{{ elem['subject'] }}</a>
</td>
<td>
    {{ data }}
</td>
<td>
    {{ time }}
</td>
<td>
    <a href="/sterge/{{ elem['id_answers'] }}/QuestionnaireResponse">
        <button type="button" class="btn btn-danger float-right">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
            </svg>
        </button>
    </a>
    <a href="/export/{{ elem['id_answers'] }}">
        <button class="btn btn-secondary float-right mr-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
            </svg>
        </button>
    </a>
</td>
<td >Tags</td>
</tr>

{% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

{% endblock %}

fhir-server.com/website/templates/question_rules.html
{% extends "base.html" %}
{% block title %}Forms{% endblock %}

{% block content %}

<script src="{{ url_for('static', filename = 'node_modules/jquery/dist/jquery.min.js') }}"></script>
<article>
<form class="needs-validation" id="formQuestion" action="{{url_for('views.formsrulessave')}}" method="post">
    <div onClick="addRule()" class="mb-2 btn btn-success">Add rule</div>
    <hr>
    <div class="" id="addRule"></div>
    
    <div class="buttons bkg-white">
        <input type="button" value="Send" class="btn btn-primary" id="btnSalveaza" onclick="salveaza()">
    </div>
</form>
   <!--
<div class="row mt-5">
    <div class="col">
        <form class="needs-validation" id="formQuestion" action="{{url_for('views.formsrulessave')}}" method="post"></form>
        <pre class="" id="rezultat"></pre>
        <div class="buttons bkg-white">
            <input type="button" value="Send" class="btn btn-primary" id="btnSalveaza" onclick="salveaza()">
        </div>
        </form>
    </div>
</div>-->

  </article>

<div id="rulesEx"></div>

  {% endblock %}
    
  {% block customJS %}

<script>
// console.log(JSON.stringify({{items|safe}}));
{% set items = continut['item'] %}
    let varTest = {{items|safe}};
    console.log(varTest);

    let allQ = [];
    let tt = [];
    let ttOpt = [];
    let ttOptV = [];
    for( t in varTest ){
        allQ.push(varTest[t]['linkId']);

        if(varTest[t]['type'] == 'choice'){

            tt.push(varTest[t]['linkId']);

            for(ttt in varTest[t]['answerOption']){
                ttOptV.push(varTest[t]['answerOption'][ttt]['valueString']);
            }
            ttOpt[varTest[t]['linkId']] = ttOptV;
            ttOptV = []; 
        }

        if(varTest[t]['type'] == 'boolean') {
            tt.push(varTest[t]['linkId']);

            ttOptV.push('true');
            ttOptV.push('false');

            // console.log('@@@@@@@@@@@@@@@@@');
            // console.log(ttOptV);
            // console.log('@@@@@@@@@@@@@@@@@');

            ttOpt[varTest[t]['linkId']] = ttOptV;
            ttOptV = []; 
        }
    };

    
//#############################################  AFISARE REGULI EXISTENTE  #########################################################
    //console.log(varTest);
    //console.log(allQ);
    let optiuni = '';

    for (i = 0; i < varTest.length; i++) {
        if('enableWhen' in varTest[i]){
            // console.log(varTest[i]);
            for(ii = 0; ii < varTest[i]['enableWhen'].length; ii++){
                // console.log(varTest[i]['enableWhen'][ii]['question']);
                question = varTest[i]['enableWhen'][ii]['question'].split('~');
                // console.log(question[1].replace('#', ''));

                let idIntrebare2 = Math.floor(Math.random() * 1001);
                let intr2 = `
                        <div class="row mt-1" id="${idIntrebare2}">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-4">
                                <select class="form-control" name="selIntrIF" id="sel${idIntrebare2}" onchange="optIntr(this.value, ${idIntrebare2})"><option></option>
                    `;

                for ( x of tt){
                    // console.log(question);
                    if(varTest[question[0]-1]['linkId'] == x){
                        intrOpt2 = `<option value="${x}" selected>${varTest[x-1]['text']}</option>`;
                        intr2 += intrOpt2;
                    } else {
                        intrOpt2 = `<option value="${x}">${varTest[x-1]['text']}</option>`;
                        intr2 += intrOpt2;
                    };
                };

                intr2 += `</select></div>`;

                // partea dreapta
                intr2 += `<div class="col-md-4"><select class="form-control" name="selRaspIf"><option value="">aici</option>`;
                linkidEW = varTest[i]['linkId'];
                for ( nrA of allQ){

                    if(varTest[nrA-1]['enableWhen'] !== undefined){
                        console.log(i);
                        console.log(' - ');
                        console.log(varTest[nrA-1]['enableWhen'][0]['question']);
                    };

                    if(allQ[nrA-1] == varTest[i]['linkId']){
                        intr2 += `<option value="${allQ[nrA-1]}" selected>${varTest[nrA-1]['text']}</option>`;
                    } else {
                        intr2 += `<option value="${allQ[nrA-1]}">${varTest[nrA-1]['text']}</option>`;
                    };
                };


                intr2 += `</select></div></div>`;
                let optiuni = '';
                if(varTest[question[0]-1]['type'] == 'boolean'){

                    intrOptiuni = `<br><input type="radio" ${question[1].replace('#', '')==1?'checked':''} name="intr~${varTest[question[0]-1]['linkId']}~`+idIntrebare2+`" id="${varTest[question[0]-1]['linkId']}~${idIntrebare2}~1" class="mt-3" value="${varTest[question[0]-1]['linkId']}~${idIntrebare2}~1"> Yes`;
                    optiuni += intrOptiuni;
                    intrOptiuni = `<br><input type="radio" ${question[1].replace('#', '')==0?'checked':''} name="intr~${varTest[question[0]-1]['linkId']}~`+idIntrebare2+`" id="${varTest[question[0]-1]['linkId']}~${idIntrebare2}~0" class="mt-3" value="${varTest[question[0]-1]['linkId']}~${idIntrebare2}~0"> No`;
                    optiuni += intrOptiuni;
                    
                };

                if(varTest[question[0]-1]['type'] == 'choice'){
                    idArr = 1;
                    for ( y of varTest[question[0]-1]['answerOption']){
                        intrOptiuni = `<br><input type="checkbox" ${idArr == question[1].replace('#','')?'checked':''} name="intr~${varTest[question[0]-1]['linkId']}~`+idIntrebare2+`" id="${idIntrebare2}~${varTest[question[0]-1]['linkId']}~`+i+`" class="mt-3" value="${idIntrebare2}~${varTest[question[0]-1]['linkId']}~`+i+`">`+y['valueString'];
                        optiuni += intrOptiuni;
                        idArr = idArr + 1;
                    }
                }
                intr2 += optiuni;

                intr2 += `<div id="optIntr${idIntrebare2}"></div>`;



                intr2 += `</div></div>`;

                $('#rulesEx').append(intr2);

            };
        };
    };



//################################################  END AFISARE REGULI EXISTENTE  ######################################################


   


    function addRule(){

        let ruleID = Math.floor(Math.random() * 1001);

        let rule = `
        <div class="row" id="rule${ruleID}">
            <div class="col-md-4">
                <div onClick="addQuestion(${ruleID})" class="mb-2 btn btn-danger">Add question</div>
                <div class="" id="question${ruleID}"></div>
            </div>
            <div class="col-md-4" id="showQuestion">
                <select class="form-control" name="selIntrShow" >
                    <option></option>`;

        for ( nrA of allQ){
            //console.log(varTest);
            // rule += `<option value="${allQ[nrA-1]}">${allQ[nrA-1]}</option>`;
            rule += `<option value="${allQ[nrA-1]}">${varTest[nrA-1]['text']}</option>`;
        };
                    rule +=`</select>
            </div>
        </div>
        <hr>
        `;

        $('#addRule').append(rule);
        
    }

    function addQuestion(idRule){
        //console.log(tt);

        let idIntrebare = Math.floor(Math.random() * 1001);

        let intrebari = tt;
        let optIntr = ttOpt;

        let intr = `
            <div class="row mt-1" id="${idIntrebare}">
                <div class="col-md-12">
                    <select class="form-control" name="selIntrIF" id="sel${idIntrebare}" onchange="optIntr(this.value, ${idIntrebare})"><option></option>
        `;
            
        for ( x of intrebari){
            intrOpt = `<option value="${x}">${varTest[x-1]['text']}</option>`;
            intr += intrOpt;
        };

        intr += `</select></div>`;
                
        // for (y of intrebari){
        //     intr += `<div id="intr${y}"></div>`;
        // }
        
        intr += `<div id="optIntr${idIntrebare}"></div>`;

        intr += `</div>`;

        $('#question' + idRule).append( intr );

    }


    function optIntr(idIntr, idDiv){
        let optIntr = ttOpt;    

        // let parentID = idDiv.parentNode.parentNode.id;
        // console.log(parentID);

        $('.intr' + idIntr).css({'display': 'block'});
        let optiuni = '';
        i = 1;

        for( t in varTest ){

            
            if(varTest[t]['linkId'] == idIntr){
                if(varTest[t]['type'] == 'boolean'){
                    //console.log('@@@@@@@@@@@');
                    //console.log(idDiv);
                    //console.log('@@@@@@@@@@@');
                    intrOptiuni = `<br><input type="radio" name="intr~${idIntr}~`+idDiv+`" id="${idDiv}~${idIntr}~1" class="mt-3" value="${idDiv}~${idIntr}~1"> Yes`;
                    optiuni += intrOptiuni;
                    intrOptiuni = `<br><input type="radio" name="intr~${idIntr}~`+idDiv+`" id="${idDiv}~${idIntr}~0" class="mt-3" value="${idDiv}~${idIntr}~0"> No`;
                    optiuni += intrOptiuni;
                    i = i + 1;

                } else if(varTest[t]['type'] == 'choice'){
                    for ( y of optIntr[idIntr]){
                        
                        intrOptiuni = `<br><input type="checkbox" name="intr~${idIntr}~`+idDiv+`" id="${idDiv}~${idIntr}~`+i+`" class="mt-3" value="${idDiv}~${idIntr}~`+i+`">`+y.replace('%20', ' ');
                        optiuni += intrOptiuni;
                        i = i + 1;
                    }
                }
            }
        }

        $('#optIntr' + idDiv).html( optiuni );

    }

    function salveaza(){
       
        var str = $( "form" ).serialize();           
//console.log(str);
        $.ajax({
            type: "post",
            url: "{{url_for('views.formsrulessave')}}",
            data: {'data':JSON.stringify(str), 'id': {{continut['id']}}},
            success: function (response) {
                // $('#rezultat').text(response);
                location.href = "/home";
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);
            }
        });
    }


</script>
{% endblock %}